language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy3
# blocklist branches
branches:
  except:
  - requires-io-master
install:
- pip install -r requirements-test.txt
- pip install -e .[tests] coveralls wheel
script:
- py.test -n 0 --cov src/pytest_rabbitmq tests
- pylama
- pyroma .
after_success:
- coveralls
jobs:
  include:
    - stage: xdist
      python: 3.6
      script: py.test -n 1 --cov src/pytest_rabbitmq tests
    - stage: deploy
      python: 3.6
      if: tag IS present
      script: skip
      deploy:
        provider: pypi
        user: thearoom
        password:
          secure: UDRSSxtaaBDrP/s0H98+PhI4DUlx0upKTcpFNh3AuNfSO5jRyL176u8V45iPkFmLrVJmPGx4qSaQ6ng0886rp0PE2DQBRocu7Vvpzh2ksNeMjMHGW4+Lw50RjSY9bbkeP3fkfb79Z3BIzZyB4xIHwf7rlToh2YNCrCD1/zSQoDATkRrEeJ1744/9Ae3CRfo5uL9VwW//X6zppiwz8FZMEuRijxjGeZU14C3DLnEfAj/hakxDqA9WuW0vIz04qNzGfym/AdhzyC77e0G46Dz49uQAurHmtV9Fv48WBuUq1C81rLNTN7QVpEx8AK7ExGHzmZ/iz7xASSYDkxwarVNH3lK/UZDcNTXT7uMZFkYAyxlJkH9GqkIQbfSdybFRb6xxYm8LkBfqG2sNxx8URDnfKb0JvZT+5x1bfKxpLkjYXtlEgzCmhIiEPfB3xn55sdebcHcDuJjCikc1X5Usxf50bHHeJX6o90pu4O+ko1sSLIGWRmcm+iCAiy1WukVYNyUer/HqHtONE2QmFB4NBn3/c1aOwjq9Gu4TlZ0AUitnjaZJYWlgCKQ7a2VRpeWEEi5K8Oj35HRrtO9EyVwMF18JDT91kZogi5mcUPduHSFMWImpsnJmHoEece+7bS4UX+c89Q17/Fl3t6g7axFiOvnZ9BBi/VseVTJCRKNOFgUVACA=
        on:
          tags: true
          all_branches: true
          repo: ClearcodeHQ/pytest-rabbitmq
        distributions: bdist_wheel
