name: Run linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    uses: fizyk/actions-reuse/.github/workflows/linters-python.yml@v2.4.5
    with:
      black: true
      ruff: true
      mypy: true
