name: Package and publish
on:
  push:
    tags:
      - v*
jobs:
  build:
    uses: fizyk/actions-reuse/.github/workflows/pypi.yml@continue-on-error
    with:
      publish: true
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
