name: Run tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - .github/workflows/tests.yml
      - requirements-test.txt
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", pypy-3.8]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update apt
      run: |
        sudo apt-get update
    - name: Install RabbitMQ
      run: |
        sudo apt-get install rabbitmq-server
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run test
      run: |
        pytest -n 0 --cov-report=xml
    - name: Run xdist test
      run: |
        pytest -n 1 --cov-report=xml:coverage-xdist.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.3
      with:
        flags: linux
        env_vars: OS, PYTHON
        fail_ci_if_error: true
